# Generated by Django 4.2.9 on 2025-05-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_tacc_remote_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecontent',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
        migrations.AlterField(
            model_name='remotecontent',
            name='remote_path',
            field=models.CharField(max_length=255),
        ),
    ]
